return {
	-- https://github.com/ThePrimeagen/harpoon
	"ThePrimeagen/harpoon",
	config = function()
		local mark = require("harpoon.mark")
		local ui = require("harpoon.ui")

		vim.keymap.set("n", "<leader>ha", mark.add_file, { desc = "Add file to harpoon" })
		vim.keymap.set("n", "<leader>ho", ui.toggle_quick_menu, { desc = "Open harpoon ui" })
		vim.keymap.set("n", "<leader>hr", mark.rm_file, { desc = "Remove file from harpoon" })
		vim.keymap.set("n", "<leader>hc", mark.clear_all, { desc = "Remove all files from harpoon" })

		vim.keymap.set("n", "<A-1>", function()
			ui.nav_file(1)
		end)
		vim.keymap.set("n", "<A-2>", function()
			ui.nav_file(2)
		end)
		vim.keymap.set("n", "<A-3>", function()
			ui.nav_file(3)
		end)
		vim.keymap.set("n", "<A-4>", function()
			ui.nav_file(4)
		end)
		vim.keymap.set("n", "<A-5>", function()
			ui.nav_file(5)
		end)
		vim.keymap.set("n", "<A-6>", function()
			ui.nav_file(6)
		end)
		vim.keymap.set("n", "<A-7>", function()
			ui.nav_file(7)
		end)
		vim.keymap.set("n", "<A-8>", function()
			ui.nav_file(8)
		end)
		vim.keymap.set("n", "<A-9>", function()
			ui.nav_file(9)
		end)
	end,
}
